manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
  projects:
    - name: cirque-input-module
      remote: petejohanson
      revision: main
      # import: west.yml
